language: node_js
node_js:
  - 12
  - 10
cache: yarn
before_script:
  - 'if [[ -n "$TRAVIS_TAG" ]] && [[ "$TRAVIS_JOB_NUMBER" == *.1 ]]; then yarn run create-github-release; fi'
jobs:
  include:
    - stage: test
      script: yarn lint
